apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 5;done"]
