apiVersion: v1
kind: Pod
metadata:
  name: nodesel-pod
  labels:
    app: nodesel
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - name: nodesel-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo nodesel; sleep 5;done"]
