apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/3 * * * *" #every 3min
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: displayDate
            image: busybox
            args:
            - /bin/sh
            - -c
            - date
          restartPolicy: OnFailure
