apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: gkepath
      mountPath: /data/shared
  volumes:
  - name : gkepath
    persistentVolumeClaim:
      claimName: gke-storage


